name: convert scss to css

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: main
            fetch-depth: 10
            submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/onscreenproton.github.io/assets/css

      - name: Compile CSS from SCSS
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: main.scss
          destination: /tmp/onscreenproton.github.io/assets/css/main.css
      
      - name: Move CSS to dest. dir
        run: mv /tmp/onscreenproton.github.io/assets/css/main.css compiled/

      - name: Commit changes
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add comiled/*
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main