name: convert scss to css

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: main
            fetch-depth: 10
            submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/onscreenproton.github.io/assets/css

      - name: Compile CSS from SCSS
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: main.scss
          destination: /tmp/onscreenproton.github.io/assets/css/main.css
      
      - name: Move CSS to dest. dir
        run: mv /tmp/onscreenproton.github.io/assets/css/main.css compiled/